### DISCUSSION TITLE
How to deploy Blazor to Azure with YAML? I´m almost there!

### DISCUSSION THREAD

**Discussion by sturlath** [abpframework/abp#7416] [Q&A]
Ok, I´m trying to deploy the apb.io Blazor to Azure using YAML. 

My two-part Azure pipeline builds everything and then publishes the code with the DB is created just fine and the Blazor part published to its web service

But **there is something that I'm missing** because I don't get any other DLL's dropped to azure but the Blazor ones and I get the following error in the browser. 

![image](https://user-images.githubusercontent.com/2386572/105477597-fb409f00-5c99-11eb-8f5a-690973eb2992.png)

The error makes total sense if half of the code is missing... and it's probably missing because of dynamic dependency discovery (or something like that)?

## So my question is
Do I need to deploy something else ( HttpApi.Host?) separately to another service and configure them to talk to each other?  Or some other trickery?

Sorry for my ignorance with this Blazor setup but I haven't tried to deploy one before! But I have been at this for 2 days now and red half the internet but in every article e.g. [this one](https://renjithvr11.medium.com/azure-devops-multi-stage-yaml-based-ci-cd-pipelines-for-blazor-app-96cdd19378d0) or [this one](https://blazorhelpwebsite.com/ViewBlogPost/10) everything just works out of the box and that's probably because there the underlying projects are strongly referenced, correct?

## Extra info
I leave the YAML pipeline code here as help for others. I have started a blog post on this that I´ll post here when finished so it would be really great to get some help with this.

## The build pipeline

```
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: release
  BuildPlatform: 'Any CPU'
  LocalPublishWebAppFolder: WebApp
  LocalPublishDbMigratorFolder: DbMigrator

steps:

- powershell: |      
      Write-Host "System.DefinitionId (9)": $(System.DefinitionId)
      Write-Host "System.DefinitionName": $(System.DefinitionName)
      Write-Host "Project GUID": $(System.TeamProjectId)
      Write-Host "BuildId is:  $(Build.BuildId)" 
      Write-Host "$(Build.SourceBranch) value is: $(Build.SourceBranch)"
      Write-Host "$(Build.ArtifactStagingDirectory) value is: $(Build.ArtifactStagingDirectory)"
  displayName: Variable output

- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: 'MyGet feed'

- task: NuGetToolInstaller@1
 
- task: NuGetCommand@2
  displayName: Nuget restore
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.config'
    externalFeedCredentials: 'MyGet feed'  

- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: build
    arguments: --configuration $(BuildConfiguration) 
    configuration: $(BuildConfiguration)
  condition: succeeded()

- task: DotNetCoreCLI@2
  displayName: Run tests
  inputs:
    command: test
    projects: '**/*.Tests.csproj'
    publishTestResults: true
    arguments: --configuration $(BuildConfiguration) --collect "Code coverage"
    nobuild: true
  condition: succeeded()

- task: DotNetCoreCLI@2
  displayName: Gather web app binaries for publication
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/*.Blazor.csproj'
    modifyOutputPath: false
    configuration: $(BuildConfiguration)
    arguments: --configuration $(BuildConfiguration) --no-restore --no-build --output $(Build.ArtifactStagingDirectory)/$(LocalPublishWebAppFolder)
    nobuild: true
  # condition: succeeded()
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: DotNetCoreCLI@2
  displayName: Gather migration app binaries for publication
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src\MySolution.DbMigrator.csproj'
    configuration: $(BuildConfiguration)
    arguments: --configuration $(BuildConfiguration) --no-restore --no-build --output $(Build.ArtifactStagingDirectory)/$(LocalPublishDbMigratorFolder)
    nobuild: true
  # condition: succeeded()
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: PublishBuildArtifacts@1
  displayName: Upload web app publication files to artifact
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/$(LocalPublishWebAppFolder)
    ArtifactName: WebApp
  # condition: succeeded()
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: PublishBuildArtifacts@1
  displayName: Upload migration app publication files to artifact
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: DbMigrator
  # condition: succeeded()
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
```

## The Release pipeline

```
trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  ConnectedServiceName: 'MyResourceManagerSubscription'
  WebAppName: 'MySolution'
  LocalPublishDbMigratorFolder: DbMigrator
  UnzippedMigrationAppFolderPath: 'UnzippedMigrationApp'
  LocalPublishWebAppFolder: WebApp
  MigratorDllFilename: 'MySolution.DbMigrator.dll'
  ConnectionStrings.DefaultConnection: $(DBConnectionString) //This swaps out the connections string with a DevOps variable

steps:
- task: AzureAppServiceManage@0
  displayName: Stop web app
  inputs:
    azureSubscription: '$(ConnectedServiceName)'
    Action: 'Stop Azure App Service'
    WebAppName: '$(WebAppName)'

- task: DownloadPipelineArtifact@2
  displayName: "Download the DbMigration artifact from the Build pipeline"
  inputs:
    source: specific 
    project: 'project guid' # This is $(System.TeamProjectId) from the Build pipeline
    pipeline: 'Build' # You can also use System.DefinitionId from the Build pipeline
    buildVersionToDownload: latest
    artifact: DbMigrator
    path: $(LocalPublishDbMigratorFolder)

- task: ExtractFiles@1
  displayName: Unzip migrator binaries
  inputs:
    archiveFilePatterns: '$(LocalPublishDbMigratorFolder)/*.zip'
    overwriteExistingFiles: true
    cleanDestinationFolder: true
    destinationFolder: '$(UnzippedMigrationAppFolderPath)'

- task: DownloadPipelineArtifact@2
  displayName: "Download the WebApp artifact from the Build pipeline"
  inputs:
    source: specific 
    project: 'project guid'
    pipeline: 'Build' 
    buildVersionToDownload: latest
    artifact: 'WebApp'
    path: $(LocalPublishWebAppFolder)

- task: FileTransform@1
  displayName: Set migrator connection string
  inputs:
    folderPath: $(UnzippedMigrationAppFolderPath)
    fileType: json
    targetFiles: appsettings.json

- powershell: 'dotnet $(MigratorDllFilename)'
  workingDirectory: $(UnzippedMigrationAppFolderPath)
  displayName: Run the EFCore migrator

- task: AzureRmWebAppDeployment@4
  displayName: Deploy web app
  inputs:
    ConnectionType: AzureRM
    azureSubscription: '$(ConnectedServiceName)'
    appType: 'webApp'
    WebAppName: '$(WebAppName)'
    packageForLinux: '$(LocalPublishWebAppFolder)/*.zip'
    # enableCustomDeployment: true
    # ExcludeFilesFromAppDataFlag: false

- task: AzureAppServiceManage@0
  displayName: Start web app
  inputs:
    azureSubscription: '$(ConnectedServiceName)'
    Action: 'Start Azure App Service'
    WebAppName: '$(WebAppName)'
```
