### ISSUE TITLE
lepton-x@preview can't change logo and brand color

### ISSUE THREAD

**Issue by joernz** [abpframework/abp#13016]
5.3 Final / Angular / EF

I followed the new doc to test the leptonx-lite theme step by step ([doc](https://docs.abp.io/en/abp/latest/Themes/LeptonXLite/angular)). 
Everything was ok until the last step, where nothing happened (the url of the png was correct):
```css
:root {
  --lpx-logo: url('/assets/images/logo.png');
  --lpx-logo-icon: url('/assets/images/logo-icon.png');
  --lpx-brand: #edae53;
}
```
I was using the alpha version of leptonx-lite (on abp 4.4), and they are working just as wanted. The step of editing the `styles` of `angular.json` was different slightly back then though.

I also tried to use different approaches to create the new 5.3 app (CLI and download from the **Get Started** page), no luck. 

--------------
Btw, a small bug when downloading: no matter the box before the **Separate Identity Server** checked or not, you will always get separated identity server.
Btw 2, when the click on login with `responseType: 'code'`, I still get this error (5.3 Final / Angular / EF):

![image](https://user-images.githubusercontent.com/75144099/173860312-49eee02f-d264-449c-b988-8ba8ad33c47b.png)
