### ISSUE TITLE
Docker-compose.yml incorrectly references the Identity Server project when OpenIddict is used

### ISSUE THREAD

**Issue by beriniwlew** [abpframework/abp#13509]
**ABP Commerical/CLI  6.0.0-rc.1**.
Blazor WebAssembly
EF Core/Postgres

Steps to reproduce:

1. Create 6.0.0-rc.1 prerelease solution using ABP Suite
2. Note etc/docker/docker-compose.yml - it contains references to compose the IdentityServer project, not the new AuthServer project

  ```
business-identity-server:
    image: modern/business-identityserver:latest
    container_name: business-identity-server
    build:
      context: ../../
      dockerfile: src/Modern.Business.IdentityServer/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - App__SelfUrl=https://localhost:44334
      - App_CorsOrigins=https://localhost:44307
      - App_RedirectAllowedUrls=https://localhost:44307
      - AuthServer__Authority=http://business-identity-server
      - AuthServer__RequireHttpsMetadata=false
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=91f91912-5ab0-49df-8166-23377efaf3cc
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Business;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;Persist Security Info=True;
      - Redis__Configuration=redis
    ports:
      - "44334:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy  
    restart: on-failure    
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network
```
