### ISSUE TITLE
Malformed docker-compose.yml using Blazor WebAssembly 

### ISSUE THREAD

**Issue by beriniwlew** [abpframework/abp#13508]
**ABP Commerical/CLI  6.0.0-rc.1**.
Blazor WebAssembly
EF Core/Postgres

The docker-compose.yml is malformed when you have a Blazor project.   
I should note that I used ABP Suite to generate this initial solution.

Steps to reproduce:

1. Create 6.0.0-rc.1 prerelease solution using ABP Suite
2. Note etc/docker/docker-compose.yml - it contains two definitions for volumes, malforming it.

```
// SNIP
    restart: on-failure
    volumes:
      - ./appsettings.json:/usr/share/nginx/html/appsettings.json
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network
```
