### ISSUE TITLE
Docker-compose.yml incorrectly references Sql Server when Postgres is used

### ISSUE THREAD

**Issue by beriniwlew** [abpframework/abp#13510]
**ABP Commerical/CLI  6.0.0-rc.1**.
Blazor WebAssembly
EF Core/Postgres

Steps to reproduce:

1. Create 6.0.0-rc.1 prerelease solution using ABP Suite
2. Note etc/docker/docker-compose.yml - it contains references to Sql Server, not the intended Postgres image

```
sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network  
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
```
