### ISSUE TITLE
EshoponAbp How to publish to the server

### ISSUE THREAD

**Issue by zhangtingwz** [abpframework/abp#13551]
I see that abp is run via tye, but I keep showing failures when I package via tye deploy

this is my tye.yaml
```
name: EShopOnAbp
registry: registry.cn-qingdao.aliyuncs.com/add948551971/eshopabp
services:
- name: auth-server
  project: apps/auth-server/src/EShopOnAbp.AuthServer/EShopOnAbp.AuthServer.csproj
  bindings:
    - protocol: https
      port: 44330
  env:
    - Kestrel__Certificates__Default__Path=../../../../etc/dev-cert/localhost.pfx
    - Kestrel__Certificates__Default__Password=8b6039b6-c67a-448b-977b-0ce6d3fcfd49

- name: identity-service
  project: services/identity/src/EShopOnAbp.IdentityService.HttpApi.Host/EShopOnAbp.IdentityService.HttpApi.Host.csproj
  bindings:
    - protocol: https
      port: 44351
  env:
    - Kestrel__Certificates__Default__Path=../../../../etc/dev-cert/localhost.pfx
    - Kestrel__Certificates__Default__Password=8b6039b6-c67a-448b-977b-0ce6d3fcfd49

- name: administration-service
  project: services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Host/EShopOnAbp.AdministrationService.HttpApi.Host.csproj
  bindings:
    - protocol: https
      port: 44353
  env:
    - Kestrel__Certificates__Default__Path=../../../../etc/dev-cert/localhost.pfx
    - Kestrel__Certificates__Default__Password=8b6039b6-c67a-448b-977b-0ce6d3fcfd49

- name: catalog-service
  project: services/catalog/src/EShopOnAbp.CatalogService.HttpApi.Host/EShopOnAbp.CatalogService.HttpApi.Host.csproj
  bindings:
    - protocol: https
      port: 44354
  env:
    - Kestrel__Certificates__Default__Path=../../../../etc/dev-cert/localhost.pfx
    - Kestrel__Certificates__Default__Password=8b6039b6-c67a-448b-977b-0ce6d3fcfd49

- name: basket-service
  project: services/basket/src/EShopOnAbp.BasketService/EShopOnAbp.BasketService.csproj
  bindings:
    - protocol: https
      port: 44355
  env:
    - Kestrel__Certificates__Default__Path=../../../../etc/dev-cert/localhost.pfx
    - Kestrel__Certificates__Default__Password=8b6039b6-c67a-448b-977b-0ce6d3fcfd49

- name: ordering-service
  project: services/ordering/src/EShopOnAbp.OrderingService.HttpApi.Host/EShopOnAbp.OrderingService.HttpApi.Host.csproj
  bindings:
    - protocol: https
      port: 44356
  env:
    - Kestrel__Certificates__Default__Path=../../../../etc/dev-cert/localhost.pfx
    - Kestrel__Certificates__Default__Password=8b6039b6-c67a-448b-977b-0ce6d3fcfd49

- name: payment-service
  project: services/payment/src/EShopOnAbp.PaymentService.HttpApi.Host/EShopOnAbp.PaymentService.HttpApi.Host.csproj
  bindings:
    - protocol: https
      port: 44357
  env:
    - Kestrel__Certificates__Default__Path=../../../../etc/dev-cert/localhost.pfx
    - Kestrel__Certificates__Default__Password=8b6039b6-c67a-448b-977b-0ce6d3fcfd49
  env_file:
    - ./.env  

- name: web-gateway
  project: gateways/web/src/EShopOnAbp.WebGateway/EShopOnAbp.WebGateway.csproj
  bindings:
    - protocol: https
      port: 44372
  env:
    - Kestrel__Certificates__Default__Path=../../../../etc/dev-cert/localhost.pfx
    - Kestrel__Certificates__Default__Password=8b6039b6-c67a-448b-977b-0ce6d3fcfd49  

- name: web-public-gateway
  project: gateways/web-public/src/EShopOnAbp.WebPublicGateway/EShopOnAbp.WebPublicGateway.csproj
  bindings:
    - protocol: https
      port: 44373
  env:
    - Kestrel__Certificates__Default__Path=../../../../etc/dev-cert/localhost.pfx
    - Kestrel__Certificates__Default__Password=8b6039b6-c67a-448b-977b-0ce6d3fcfd49

- name: public-web
  project: apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbp.PublicWeb.csproj
  bindings:
    - protocol: https
      port: 44335
  env:
    - Kestrel__Certificates__Default__Path=../../../../etc/dev-cert/localhost.pfx
    - Kestrel__Certificates__Default__Password=8b6039b6-c67a-448b-977b-0ce6d3fcfd49
```

This is the result of my run
```
PS D:\work\eshopabp\eShopOnAbp-main (2)\eShopOnAbp-main> tye deploy
Loading Application Details...
Verifying kubectl installation...
Verifying kubectl connection to cluster...
Processing Service 'auth-server'...
    Applying container defaults...
    Compiling Services...
    Publishing Project...
    Building Docker Image...

            #8 CANCELED

            #10 [internal] load build context
            #10 sha256:46d709b2e7e1f0f84d357ead460fbc825bd1545ffd2917f76bd8f45926d04a6a
            #10 transferring context: 66.90MB 5.1s done
            #10 DONE 5.1s

            #9 [build  2/23] WORKDIR /src
            #9 sha256:aad28411a5590669fae4d669766d90a701c87e11d8196e47d1ab1800d66adf6b
            #9 CACHED

            #11 [build  3/23] COPY EShopOnAbp.sln EShopOnAbp.sln
            #11 sha256:7efa2e164996ecc89498cd2b09ebebbfac5fcbbbdf615feb2ba07de2e0bdca81
            #11 ERROR: "/EShopOnAbp.sln" not found: not found

            #18 [build 10/23] COPY shared/EShopOnAbp.Shared.Localization/EShopOnAbp.Shared.Localization.csproj shared/EShopOnAbp.Shared.Localization/EShopOnAbp.Shared.Localization.csproj
            #18 sha256:7c93428aca1bf5b33fa340e49ac9cc574af9df3b7ca19ff25010d578e5021375
            #18 ERROR: "/shared/EShopOnAbp.Shared.Localization/EShopOnAbp.Shared.Localization.csproj" not found: not found

            #17 [build  9/23] COPY shared/EShopOnAbp.Shared.Hosting.Microservices/EShopOnAbp.Shared.Hosting.Microservices.csproj shared/EShopOnAbp.Shared.Hosting.Microservices/EShopOnAbp.Shared.Hosting.Microservices.csproj
            #17 sha256:e8ce509830cf22b00ac6aa93bfde98941d8f5fb5e0502382b4eb6f3e18ad2c0d
            #17 ERROR: "/shared/EShopOnAbp.Shared.Hosting.Microservices/EShopOnAbp.Shared.Hosting.Microservices.csproj" not found: not found

            #16 [build  8/23] COPY shared/EShopOnAbp.Shared.Hosting.Gateways/EShopOnAbp.Shared.Hosting.Gateways.csproj shared/EShopOnAbp.Shared.Hosting.Gateways/EShopOnAbp.Shared.Hosting.Gateways.csproj
            #16 sha256:80d7a52d1a19ef6bb5ec0c61fe8ae304b07f3974b0dfbecd484706eb36b945cd
            #16 ERROR: "/shared/EShopOnAbp.Shared.Hosting.Gateways/EShopOnAbp.Shared.Hosting.Gateways.csproj" not found: not found

            #15 [build  7/23] COPY shared/EShopOnAbp.Shared.Hosting.AspNetCore/EShopOnAbp.Shared.Hosting.AspNetCore.csproj shared/EShopOnAbp.Shared.Hosting.AspNetCore/EShopOnAbp.Shared.Hosting.AspNetCore.csproj
            #15 sha256:aa0fc79101e89396ceb9efa6750edf1e26f21bdb5f8b9f0e2ddcd5d09f69b6c2
            #15 ERROR: "/shared/EShopOnAbp.Shared.Hosting.AspNetCore/EShopOnAbp.Shared.Hosting.AspNetCore.csproj" not found: not found

            #14 [build  6/23] COPY shared/EShopOnAbp.Shared.Hosting/EShopOnAbp.Shared.Hosting.csproj shared/EShopOnAbp.Shared.Hosting/EShopOnAbp.Shared.Hosting.csproj
            #14 sha256:d2084629fed86f7c455bfb52e3929e2a925693312bea9ccc4a918f1cfdd8f036
            #14 ERROR: "/shared/EShopOnAbp.Shared.Hosting/EShopOnAbp.Shared.Hosting.csproj" not found: not found

            #13 [build  5/23] COPY apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbp.PublicWeb.csproj apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbp.PublicWeb.csproj
            #13 sha256:35c7ddbfc896e30349ba6104bf9caeac4077d0f4db76e31be478f7e122cf8aeb
            #13 ERROR: "/apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbp.PublicWeb.csproj" not found: not found

            #12 [build  4/23] COPY apps/auth-server/src/EShopOnAbp.AuthServer/EShopOnAbp.AuthServer.csproj apps/auth-server/src/EShopOnAbp.AuthServer/EShopOnAbp.AuthServer.csproj
            #12 sha256:ec547e0242c5df70a5d9c0625008589f388a24e190917a13fd0be9ddbb2bc770
            #12 ERROR: "/apps/auth-server/src/EShopOnAbp.AuthServer/EShopOnAbp.AuthServer.csproj" not found: not found

            #19 [build 11/23] COPY services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Host/EShopOnAbp.AdministrationService.HttpApi.Host.csproj services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Host/EShopOnAbp.AdministrationService.HttpApi.Host.csproj
            #19 sha256:f060d711290b8acad389ac8f4a7328a78ba912351e9ff4c665e40f2520b98b1f
            #19 ERROR: "/services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Host/EShopOnAbp.AdministrationService.HttpApi.Host.csproj" not found: not found

            #27 [build 19/23] COPY NuGet.Config NuGet.Config
            #27 sha256:57d251e10a0e5775a538bd39d75ad66f9fead4187428b6925f185df049e43162
            #27 ERROR: "/NuGet.Config" not found: not found

            #26 [build 18/23] COPY gateways/web-public/src/EShopOnAbp.WebPublicGateway/EShopOnAbp.WebPublicGateway.csproj gateways/web-public/src/EShopOnAbp.WebPublicGateway/EShopOnAbp.WebPublicGateway.csproj
            #26 sha256:1c3e196e17a68ef48cfc3df098a6b8f36bc7d2c7b21c335c4d257ff40eec18c2
            #26 ERROR: "/gateways/web-public/src/EShopOnAbp.WebPublicGateway/EShopOnAbp.WebPublicGateway.csproj" not found: not found

            #25 [build 17/23] COPY gateways/web/src/EShopOnAbp.WebGateway/EShopOnAbp.WebGateway.csproj gateways/web/src/EShopOnAbp.WebGateway/EShopOnAbp.WebGateway.csproj
            #25 sha256:12c59ee12c3ca8ae1113d9c3d59267b7ce7eec1442a56860563495621479ef95
            #25 ERROR: "/gateways/web/src/EShopOnAbp.WebGateway/EShopOnAbp.WebGateway.csproj" not found: not found

            #24 [build 16/23] COPY services/payment/src/EShopOnAbp.PaymentService.HttpApi.Host/EShopOnAbp.PaymentService.HttpApi.Host.csproj services/payment/src/EShopOnAbp.PaymentService.HttpApi.Host/EShopOnAbp.PaymentService.HttpApi.Host.csproj
            #24 sha256:cadcb270dfba933ac4198eb439781fe18cb404ff1f3263b39ea95ed5d4a7248b
            #24 ERROR: "/services/payment/src/EShopOnAbp.PaymentService.HttpApi.Host/EShopOnAbp.PaymentService.HttpApi.Host.csproj" not found: not found

            #23 [build 15/23] COPY services/catalog/src/EShopOnAbp.CatalogService.HttpApi.Host/EShopOnAbp.CatalogService.HttpApi.Host.csproj services/catalog/src/EShopOnAbp.CatalogService.HttpApi.Host/EShopOnAbp.CatalogService.HttpApi.Host.csproj
            #23 sha256:0a9cb9ef4e8f9b55a3940b675b7a0b16bdba8970d04aa116ab209d4bcca0e56d
            #23 ERROR: "/services/catalog/src/EShopOnAbp.CatalogService.HttpApi.Host/EShopOnAbp.CatalogService.HttpApi.Host.csproj" not found: not found

            #22 [build 14/23] COPY services/ordering/src/EShopOnAbp.OrderingService.HttpApi.Host/EShopOnAbp.OrderingService.HttpApi.Host.csproj services/ordering/src/EShopOnAbp.OrderingService.HttpApi.Host/EShopOnAbp.OrderingService.HttpApi.Host.csproj
            #22 sha256:2eca97224b15087535cca38a51fda7986b776f9f9da1f6308aa10516f6dc128a
            #22 ERROR: "/services/ordering/src/EShopOnAbp.OrderingService.HttpApi.Host/EShopOnAbp.OrderingService.HttpApi.Host.csproj" not found: not found

            #21 [build 13/23] COPY services/basket/src/EShopOnAbp.BasketService/EShopOnAbp.BasketService.csproj services/basket/src/EShopOnAbp.BasketService/EShopOnAbp.BasketService.csproj
            #21 sha256:003cce60d5d9f7aff59bf34978fb1b1d7bfb560048f5fc2cd93cb5b0220b6267
            #21 ERROR: "/services/basket/src/EShopOnAbp.BasketService/EShopOnAbp.BasketService.csproj" not found: not found

            #20 [build 12/23] COPY services/identity/src/EShopOnAbp.IdentityService.HttpApi.Host/EShopOnAbp.IdentityService.HttpApi.Host.csproj services/identity/src/EShopOnAbp.IdentityService.HttpApi.Host/EShopOnAbp.IdentityService.HttpApi.Host.csproj
            #20 sha256:baaf191af03502518a1c13b94eda7a89e8fe4f1711e01f7a14f89bd8f5b06d2d
            #20 ERROR: "/services/identity/src/EShopOnAbp.IdentityService.HttpApi.Host/EShopOnAbp.IdentityService.HttpApi.Host.csproj" not found: not found

            #5 [base 1/2] FROM mcr.microsoft.com/dotnet/aspnet:6.0@sha256:55973d59f8ffd46af48ee247c847ec97ab04ae12d09f178720d615a62faa363c
            #5 sha256:8f7a83cacf750e15b8f3045e9f31ab87d6eb419e43955bac1abded1d3c940dae
            #5 resolve mcr.microsoft.com/dotnet/aspnet:6.0@sha256:55973d59f8ffd46af48ee247c847ec97ab04ae12d09f178720d615a62faa363c done
            #5 sha256:55973d59f8ffd46af48ee247c847ec97ab04ae12d09f178720d615a62faa363c 2.17kB / 2.17kB done
            #5 sha256:c18bf333fff9856b144265ce710ca29d42729c701760564c4326c065d707f718 1.37kB / 1.37kB done
            #5 sha256:0f90854fdedd75e509d249c45d2bbde2dcadeee4f71fa3128d1a8ea29813a905 3.25kB / 3.25kB done
            #5 sha256:1efc276f4ff952c055dea726cfc96ec6a4fdb8b62d9eed816bd2b788f2860ad7 31.37MB / 31.37MB 3.3s done
            #5 sha256:4db5fdd9a634cf27fd4625f3fe4228553255e4a3d08042b1554114b2aec10172 15.17MB / 15.17MB 1.8s done
            #5 sha256:f753f2ec9b28960fac0f8943e3f7eb40b4c138088e4e683177b1ae86d16c284d 31.62MB / 31.62MB 3.3s done
            #5 sha256:77af49007a1781882dd5709e36571cbb56503e0f03e3a006b4bccf2963e8d5d5 156B / 156B 2.0s done
            #5 sha256:e68a80a07af89b1272001c9576436ef9450bbe8ac2ff32c9684927af79262c6e 9.46MB / 9.46MB 3.0s done
            #5 CANCELED
            ------
             > [build  3/23] COPY EShopOnAbp.sln EShopOnAbp.sln:
            ------
            ------
             > [build  4/23] COPY apps/auth-server/src/EShopOnAbp.AuthServer/EShopOnAbp.AuthServer.csproj apps/auth-server/src/EShopOnAbp.AuthServer/EShopOnAbp.AuthServer.csproj:
            ------
            ------
             > [build  5/23] COPY apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbp.PublicWeb.csproj apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbp.PublicWeb.csproj:
            ------
            ------
             > [build  6/23] COPY shared/EShopOnAbp.Shared.Hosting/EShopOnAbp.Shared.Hosting.csproj shared/EShopOnAbp.Shared.Hosting/EShopOnAbp.Shared.Hosting.csproj:
            ------
            ------
             > [build  7/23] COPY shared/EShopOnAbp.Shared.Hosting.AspNetCore/EShopOnAbp.Shared.Hosting.AspNetCore.csproj shared/EShopOnAbp.Shared.Hosting.AspNetCore/EShopOnAbp.Shared.Hosting.AspNetCore.csproj:
            ------
            ------
             > [build  8/23] COPY shared/EShopOnAbp.Shared.Hosting.Gateways/EShopOnAbp.Shared.Hosting.Gateways.csproj shared/EShopOnAbp.Shared.Hosting.Gateways/EShopOnAbp.Shared.Hosting.Gateways.csproj:
            ------
            ------
             > [build  9/23] COPY shared/EShopOnAbp.Shared.Hosting.Microservices/EShopOnAbp.Shared.Hosting.Microservices.csproj shared/EShopOnAbp.Shared.Hosting.Microservices/EShopOnAbp.Shared.Hosting.Microservices.csproj:
            ------
            ------
             > [build 10/23] COPY shared/EShopOnAbp.Shared.Localization/EShopOnAbp.Shared.Localization.csproj shared/EShopOnAbp.Shared.Localization/EShopOnAbp.Shared.Localization.csproj:
            ------
            ------
             > [build 11/23] COPY services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Host/EShopOnAbp.AdministrationService.HttpApi.Host.csproj services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Host/EShopOnAbp.AdministrationService.HttpApi.Host.csproj:
            ------
            ------
             > [build 12/23] COPY services/identity/src/EShopOnAbp.IdentityService.HttpApi.Host/EShopOnAbp.IdentityService.HttpApi.Host.csproj services/identity/src/EShopOnAbp.IdentityService.HttpApi.Host/EShopOnAbp.IdentityService.HttpApi.Host.csproj:
            ------
            ------
             > [build 13/23] COPY services/basket/src/EShopOnAbp.BasketService/EShopOnAbp.BasketService.csproj services/basket/src/EShopOnAbp.BasketService/EShopOnAbp.BasketService.csproj:
            ------
            ------
             > [build 14/23] COPY services/ordering/src/EShopOnAbp.OrderingService.HttpApi.Host/EShopOnAbp.OrderingService.HttpApi.Host.csproj services/ordering/src/EShopOnAbp.OrderingService.HttpApi.Host/EShopOnAbp.OrderingService.HttpApi.Host.csproj:
            ------
            ------
             > [build 15/23] COPY services/catalog/src/EShopOnAbp.CatalogService.HttpApi.Host/EShopOnAbp.CatalogService.HttpApi.Host.csproj services/catalog/src/EShopOnAbp.CatalogService.HttpApi.Host/EShopOnAbp.CatalogService.HttpApi.Host.csproj:
            ------
            ------
             > [build 16/23] COPY services/payment/src/EShopOnAbp.PaymentService.HttpApi.Host/EShopOnAbp.PaymentService.HttpApi.Host.csproj services/payment/src/EShopOnAbp.PaymentService.HttpApi.Host/EShopOnAbp.PaymentService.HttpApi.Host.csproj:
            ------
            ------
             > [build 17/23] COPY gateways/web/src/EShopOnAbp.WebGateway/EShopOnAbp.WebGateway.csproj gateways/web/src/EShopOnAbp.WebGateway/EShopOnAbp.WebGateway.csproj:
            ------
            ------
             > [build 18/23] COPY gateways/web-public/src/EShopOnAbp.WebPublicGateway/EShopOnAbp.WebPublicGateway.csproj gateways/web-public/src/EShopOnAbp.WebPublicGateway/EShopOnAbp.WebPublicGateway.csproj:
            ------
            ------
             > [build 19/23] COPY NuGet.Config NuGet.Config:
            ------
            failed to compute cache key: "/NuGet.Config" not found: not found
Drats! 'deploy' failed:
        'docker build' failed.
```

Please help me thank you
