### ISSUE TITLE
LeptonX side menu styles conflict

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#13817]
I am trying to use the `table-sm` class on a `dataTable` and I want it to have less padding on the cells, but the `LeptonXLite\Global\side-menu\css\js-bundle.css` stylesheet is conflicting with the generic dataTable styling. Please could you add `.userMenu` selectors to the styles? This may extend further than just data tables, it may need reviewing.

```html
<abp-table striped-rows="true" id="MyTable" class="table-sm"></abp-table>
```

These are the styles I have written to fix some of the issues I have seen:
```css
table.dataTable.table-sm tbody tr th,
table.dataTable.table-sm tbody tr td {
    padding: 0.438rem 0.5rem;
}
table.dataTable.table-sm .sorting:after, 
table.dataTable.table-sm .sorting_asc:after, 
table.dataTable.table-sm .sorting_desc:after {
    top: 0px;
}
table.dataTable.table-sm thead th {
    padding: 0.438rem 0.5rem !important;
}
.table.table-striped > tbody > tr:nth-of-type(odd):hover > td,
.table.table-bordered > tbody > tr:nth-of-type(odd):hover > td {
    --bs-table-accent-bg: var(--bs-table-hover-bg);
}
```
