### ISSUE TITLE
How can I mark a nullable Enum as 'nullable: true' in Swagger?

### ISSUE THREAD

**Issue by hexianggui** [abpframework/abp#18448]
How can I mark a nullable Enum as 'nullable: true' in Swagger? For example, my DTO is as follows:
```
public class TestDto
{
    public long Id { get; set; }
    public string? Name2 { get; set; }
    public NullAbleTestEnum? TestEnum { get; set; }
    public int? Name3 { get; set; }
}

public enum NullAbleTestEnum
{
    One,
    Two,
    Three
}
```
In Swagger:

```
Acme.BookStore.Dtos.TestDto {
  id: integer($int64)
  name2: string
  nullable: true
  testEnum: Acme.BookStore.Dtos.NullAbleTestEnum string
  Enum:
    Array [ 3 ]
  name3: integer($int32)
  nullable: true
}
```
The TestEnum does not have the 'nullable: true'tag. In the frontend interface, TestEnum is not recognized as 'NullAbleTestEnum | undefined'.
