### ISSUE TITLE
Font icon garbled after Styles Bundling

### ISSUE THREAD

**Issue by myesn** [abpframework/abp#20602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

```css
.fa.fa-star-o:before {
    content: "ï€…"
}

.fa.fa-remove:before {
    content: "ï€"
}

.fa.fa-close:before {
    content: "ï€"
}
```
![image](https://github.com/user-attachments/assets/dbf4098a-236a-431d-9b7d-c6a3ef89dd90)

![image](https://github.com/user-attachments/assets/89a7e293-52e7-4a4e-9ed2-d490f46071e6)

![image](https://github.com/user-attachments/assets/a99b1cc4-3458-4b45-91dd-f5c6d541d971)

![image](https://github.com/user-attachments/assets/fafc88ec-1f27-415b-b495-ec13db9d86e1)

### Version

8.1.0

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)
