### ISSUE TITLE
Angular template - modal backdrop is being cut if modal height is higher than 100%

### ISSUE THREAD

**Issue by thiag0coelho** [abpframework/abp#2487]
![image](https://user-images.githubusercontent.com/6138475/71544889-2061c180-2963-11ea-8bf3-eeccf4b8885c.png)
When form is too large modal backdrop is being cut, it's max height is 100%

Tried to make a PR to fix this issue changing scss like so

```
.modal-backdrop {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 1040;
    background-color: #000;
    opacity: 0.6;
}
```

But then scrolling on backdrop does not work. I'll leave it to you

**Comment by mehmet-erim** [comment]
Hi @thiag0coelho
I haven't seen any problem.
Which version of `@abp/ng.theme.shared` is installed in your application?

The current version is 1.1.1 and `.modal-backdrop` styles like this:
```css
.modal-backdrop {
  position: fixed;
  top: 0;
  left: 0;
  width: calc(100% - 7px);
  height: 100%;
  background-color: rgba(0, 0, 0, 0.6);
  z-index: 1040;
}
```
