### ISSUE TITLE
Gulp - copyResources producing a wrong result

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#4547]
Hi,

I'm currently working on a corporate CI theme and experiencing issues with the abp gulpfile.
To follow the ABP guidelines, I've created some standard packages, which are currently under our company scope.

Let's take the following package:

**package.json**
```yml
{
    "name": "@lis/devextreme-aspnet-data",
    "version": "2.9.5",
    "author": "Necati Meral <nm@lis-gmbh.com>",
    "license": "UNLICENSED",
    "dependencies": {
        "devextreme-aspnet-data": "^2.6.2"
    },
    "gitHead": "eacb52c3fc11be1915d266b6ffe5583bf1286e17"
}
```

**abp.resourcemapping.js**
```js
module.exports = {
    mappings: {
        "@node_modules/devextreme-aspnet-data/js/dx.aspnet.data.js": "@libs/devextreme-aspnet-data/dx.aspnet.data.js"
    }
}
``` 

**Expected result**
![grafik](https://user-images.githubusercontent.com/7882753/86135532-3fe0cf00-baeb-11ea-9ec5-0f82e904815b.png)

**Actual result**
![grafik](https://user-images.githubusercontent.com/7882753/86135779-8f26ff80-baeb-11ea-979f-1ae1a1082718.png)

As far I've seen, this occurs only when specifying a file and not when specifying a directory inside the resourcemapping.
Another resourcemapping, which works totally fine:

**abp.resourcemapping.js**
```js
module.exports = {
    mappings: {
        "@node_modules/cldr-data/main/*.*": "@libs/cldr-data/main/",
        "@node_modules/cldr-data/segments/*.*": "@libs/cldr-data/segments/",
        "@node_modules/cldr-data/supplemental/*.*": "@libs/cldr-data/supplemental/"
    }
}
```
