### ISSUE TITLE
Trying to deploy to Azure

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#7743]
* Your **ABP Framework version** - v4.2.0
* Your **User Interface** - MVC
* Your database provider - EFCore
* Exception message and **stack trace** if available (check the logs).

![image](https://user-images.githubusercontent.com/15242923/108036674-a28fd680-708c-11eb-824c-224dcd5e0362.png)

* Steps needed to **reproduce** the problem.

Below is my my Yaml

```
steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(Parameters.projects)'
    feedsToUse: config
    nugetConfigPath: 'aspnet-core/NuGet.Config'
    restoreDirectory: 'NexBase/aspnet-core/NuGet.Config'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(Parameters.projects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
```
