### ISSUE TITLE
Details of the Blazor dialog modal will overflow if the text is too long.

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#7991]
When the detail is too long, it overflows:

![K6SM___V6SRKCQ`LG_OZ_IN](https://user-images.githubusercontent.com/30018771/110320428-3aa92c00-804b-11eb-9c5c-50174c7bc9cd.png)

if I add this code to `main.css`:
```css
.modal .modal-dialog .modal-content {
    word-wrap: break-word;
    word-break: normal;
}
```

the problem will be solved:

![8UWGH(@YCNAX_V{5~{5GGJJ](https://user-images.githubusercontent.com/30018771/110320849-dfc40480-804b-11eb-8ea3-6a041138e2ab.png)
